"""Normalized domain exceptions."""

from app.exceptions.domain import (
    AdapterNotAvailableError,
    CatalogRequestError,
    CatalogSnapshotNotFoundError,
    ConfigurationError,
    ConnectionDisabledError,
    ConnectionNotFoundError,
    DatabaseObjectNotFoundError,
    DatabaseOperationError,
    DataPlatformError,
    GenerationNotConfiguredError,
    GenerationProviderError,
    GenerationProviderNotAvailableError,
    GenerationRequestError,
    LlmExplanationParseError,
    LlmGenerationParseError,
    ReportFormatNotSupportedError,
    ReportingNotConfiguredError,
    ReportPeriodInvalidError,
    ReportTooLargeError,
    SecretNotConfiguredError,
)

__all__ = [
    "AdapterNotAvailableError",
    "CatalogRequestError",
    "CatalogSnapshotNotFoundError",
    "ConfigurationError",
    "ConnectionDisabledError",
    "ConnectionNotFoundError",
    "DataPlatformError",
    "DatabaseObjectNotFoundError",
    "DatabaseOperationError",
    "GenerationNotConfiguredError",
    "GenerationProviderError",
    "GenerationProviderNotAvailableError",
    "GenerationRequestError",
    "LlmExplanationParseError",
    "LlmGenerationParseError",
    "ReportFormatNotSupportedError",
    "ReportPeriodInvalidError",
    "ReportTooLargeError",
    "ReportingNotConfiguredError",
    "SecretNotConfiguredError",
]
